---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "mariadb"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "mariadb"

- name: Copying over galera.cnf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/galera.cnf.j2"
      - "{{ node_custom_config }}/galera.cnf"
      - "{{ node_custom_config }}/mariadb/{{ inventory_hostname }}/galera.cnf"
    dest: "{{ node_config_directory }}/{{ item }}/galera.cnf"
  with_items:
    - "mariadb"

- name: Copying over wsrep-notify.sh
  template:
    src: "{{ role_path }}/templates/wsrep-notify.sh.j2"
    dest: "{{ node_config_directory }}/{{ item }}/wsrep-notify.sh"
  with_items:
    - "mariadb"
