---
project_name: "mistral"

####################
# Database
####################
mistral_database_name: "mistral"
mistral_database_user: "mistral"
mistral_database_address: "{{ kolla_internal_fqdn }}:{{ database_port }}"


####################
# Docker
####################
mistral_engine_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mistral-engine"
mistral_engine_tag: "{{ openstack_release }}"
mistral_engine_image_full: "{{ mistral_engine_image }}:{{ mistral_engine_tag }}"

mistral_executor_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mistral-executor"
mistral_executor_tag: "{{ openstack_release }}"
mistral_executor_image_full: "{{ mistral_executor_image }}:{{ mistral_executor_tag }}"

mistral_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-mistral-api"
mistral_api_tag: "{{ openstack_release }}"
mistral_api_image_full: "{{ mistral_api_image }}:{{ mistral_api_tag }}"


####################
# OpenStack
####################
mistral_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ mistral_api_port }}/v2"
mistral_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ mistral_api_port }}/v2"
mistral_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ mistral_api_port }}/v2"

mistral_logging_debug: "{{ openstack_logging_debug }}"

mistral_keystone_user: "mistral"

openstack_mistral_auth: "{'auth_url':'{{ openstack_auth.auth_url }}','username':'{{ openstack_auth.username }}','password':'{{ openstack_auth.password }}','project_name':'{{ openstack_auth.project_name }}'}"
