---
- name: Starting glance-registry container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ glance_registry_image_full }}"
    name: "glance_registry"
    volumes:
      - "{{ node_config_directory }}/glance-registry/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['glance-registry']

- name: Starting glance-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ glance_api_image_full }}"
    name: "glance_api"
    volumes:
      - "{{ node_config_directory }}/glance-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "glance:/var/lib/glance/"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['glance-api']
