---
- name: Check if Keystone Domain specific settings enabled
  local_action: stat path="{{ node_custom_config }}/keystone/domains"
  register: keystone_domain_cfg

- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "keystone"

- name: Creating Keystone Domain directory
  file:
    dest: "{{ node_config_directory }}/{{ item }}/domains/"
    state: "directory"
  when:
      keystone_domain_cfg.stat.exists
  with_items:
    - "keystone"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "keystone"

- name: Copying over keystone.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/keystone.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/keystone.conf"
      - "{{ node_custom_config }}/keystone/{{ inventory_hostname }}/keystone.conf"
    dest: "{{ node_config_directory }}/{{ item }}/keystone.conf"
  with_items:
    - "keystone"

- name: Copying Keystone Domain specific settings
  copy:
    src: "{{ item }}"
    dest: "{{ node_config_directory }}/keystone/domains/"
  with_fileglob:
    - "{{ node_custom_config }}/keystone/domains/*"

- name: Copying over wsgi-keystone.conf
  template:
    src: "wsgi-keystone.conf.j2"
    dest: "{{ node_config_directory }}/keystone/wsgi-keystone.conf"
