---
- name: Starting ceph-mon container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      HOSTNAME: "{{ storage_hostname }}"
    image: "{{ ceph_mon_image_full }}"
    name: "ceph_mon"
    volumes:
      - "{{ node_config_directory }}/ceph-mon/:{{ container_config_directory }}/:ro"
      - "ceph_mon:/var/lib/ceph"
      - "ceph_mon_config:/etc/ceph"
  when: inventory_hostname in groups['ceph-mon']
