---
# enforce ironic usage only with openvswitch
- include: ironic-check.yml

- include: register.yml
  when: inventory_hostname in groups['neutron-server']

- include: config.yml
  when: inventory_hostname in groups['compute']
        or (enable_manila | bool and inventory_hostname in groups['manila-share'])
        or inventory_hostname in groups['neutron-dhcp-agent']
        or inventory_hostname in groups['neutron-l3-agent']
        or inventory_hostname in groups['neutron-metadata-agent']
        or inventory_hostname in groups['neutron-server']
        or inventory_hostname in groups['neutron-lbaas-agent']
        or inventory_hostname in groups['neutron-vpnaas-agent']

- include: config-neutron-fake.yml
  when:
    - inventory_hostname in groups['compute']
    - enable_nova_fake | bool

- include: bootstrap.yml
  when: inventory_hostname in groups['neutron-server']

- include: start.yml
  when: inventory_hostname in groups['compute']
        or (enable_manila | bool and inventory_hostname in groups['manila-share'])
        or inventory_hostname in groups['neutron-dhcp-agent']
        or inventory_hostname in groups['neutron-l3-agent']
        or inventory_hostname in groups['neutron-metadata-agent']
        or inventory_hostname in groups['neutron-server']
        or inventory_hostname in groups['neutron-lbaas-agent']
        or inventory_hostname in groups['neutron-vpnaas-agent']
