---
- name: Pulling neutron-dhcp-agent image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ neutron_dhcp_agent_image_full }}"
  when: inventory_hostname in groups['neutron-dhcp-agent']

- name: Pulling neutron-l3-agent image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ neutron_l3_agent_image_full }}"
  when: inventory_hostname in groups['neutron-l3-agent']

- name: Pulling neutron-linuxbridge-agent image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ neutron_linuxbridge_agent_image_full }}"
  when:
    - (inventory_hostname in groups['compute']
       or (enable_manila | bool and inventory_hostname in groups['manila-share'])
       or inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent']
       or inventory_hostname in groups['neutron-vpnaas-agent'])
    - neutron_plugin_agent == "linuxbridge"

- name: Pulling neutron-metadata-agent image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ neutron_metadata_agent_image_full }}"
  when: inventory_hostname in groups['neutron-metadata-agent']

- name: Pulling neutron-openvswitch-agent image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ neutron_openvswitch_agent_image_full }}"
  when:
    - (inventory_hostname in groups['compute']
       or (enable_manila | bool and inventory_hostname in groups['manila-share'])
       or inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent']
       or inventory_hostname in groups['neutron-vpnaas-agent'])
    - neutron_plugin_agent == "openvswitch"

- name: Pulling neutron-server image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ neutron_server_image_full }}"
  when: inventory_hostname in groups['neutron-server']

- name: Pulling openvswitch-db image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ openvswitch_db_image_full }}"
  when:
    - (inventory_hostname in groups['compute']
       or (enable_manila | bool and inventory_hostname in groups['manila-share'])
       or inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent']
       or inventory_hostname in groups['neutron-vpnaas-agent'])
    - neutron_plugin_agent == "openvswitch"

- name: Pulling openvswitch-vswitchd image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ openvswitch_vswitchd_image_full }}"
  when:
    - (inventory_hostname in groups['compute']
       or (enable_manila | bool and inventory_hostname in groups['manila-share'])
       or inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent']
       or inventory_hostname in groups['neutron-vpnaas-agent'])
    - neutron_plugin_agent == "openvswitch"
