---
- include: register.yml
  when: inventory_hostname in groups['congress-api']

- include: config.yml
  when: inventory_hostname in groups['congress-api'] or
        inventory_hostname in groups['congress-policy-engine'] or
        inventory_hostname in groups['congress-datasource']

- include: bootstrap.yml
  when: inventory_hostname in groups['congress-api']

- include: start.yml
  when: inventory_hostname in groups['congress-api'] or
        inventory_hostname in groups['congress-policy-engine'] or
        inventory_hostname in groups['congress-datasource']
