---
- name: Starting horizon container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ horizon_image_full }}"
    name: "horizon"
    volumes:
      - "{{ node_config_directory }}/horizon/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['horizon']
