---
- name: Checking that libvirt is not running
  stat: path=/var/run/libvirt/libvirt-sock
  register: result
  failed_when: result.stat.exists
  when: inventory_hostname in groups['compute']

- name: Checking Docker version
  command: docker version
  register: result
  changed_when: false
  failed_when: result | failed
               or (result.stdout | from_yaml).Server.Version | regex_replace('(\\d+\\.\\d+\\.\\d+).*', '\\1') | version_compare(docker_version_min, '<')

- name: Checking if 'MountFlags' in /lib/systemd/system/docker.service is set to 'shared'
  command: cat /lib/systemd/system/docker.service
  register: result
  changed_when: false
  failed_when: result.stdout.find('MountFlags=shared') == -1
  when:
    - (inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent'])
    - ansible_os_family == 'RedHat'
       or (ansible_distribution == 'Ubuntu' and ansible_distribution_version > '14.04')

- name: Checking if '/run' mount flag is set to 'shared'
  command: awk '$5 == "/run" {print $7}' /proc/self/mountinfo
  register: result
  changed_when: false
  failed_when: result.stdout.find('shared') == -1
  when:
    - (inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent'])
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Checking empty passwords in /etc/kolla/passwords.yml. Run kolla-genpwd is this task fails
  local_action: command grep '^[^#].*:\s*$' /etc/kolla/passwords.yml
  register: result
  changed_when: false
  failed_when: result.stdout != ""
