---
- name: Checking that libvirt is not running
  stat: path=/var/run/libvirt/libvirt-sock
  register: result
  failed_when: result.stat.exists
  when: inventory_hostname in groups['compute']

- name: Checking Docker version
  command: docker version
  register: result
  changed_when: false
  failed_when: result | failed
               or (result.stdout | from_yaml).Server.Version | regex_replace('(\\d+\\.\\d+\\.\\d+).*', '\\1') | version_compare(docker_version_min, '<')

# When MountFlags is set to shared, a signal bit configured on 20th bit of a number
# We need to check the 20th bit. 2^20 = 1048576. So we are validating against it.
- name: Checking if 'MountFlags' for docker service is set to 'shared'
  command: systemctl show docker
  register: result
  changed_when: false
  failed_when: result.stdout.find('MountFlags=1048576') == -1
  when:
    - (inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent'])
    - ansible_os_family == 'RedHat'
       or (ansible_distribution == 'Ubuntu' and ansible_distribution_version > '14.04')

- name: Checking if '/run' mount flag is set to 'shared'
  command: awk '$5 == "/run" {print $7}' /proc/self/mountinfo
  register: result
  changed_when: false
  failed_when: result.stdout.find('shared') == -1
  when:
    - (inventory_hostname in groups['neutron-dhcp-agent']
       or inventory_hostname in groups['neutron-l3-agent']
       or inventory_hostname in groups['neutron-metadata-agent'])
    - ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Checking empty passwords in passwords.yml. Run kolla-genpwd if this task fails
  local_action: command grep '^[^#].*:\s*$' "{{ CONFIG_DIR }}/passwords.yml"
  register: result
  changed_when: false
  failed_when: result.stdout | regex_replace('(.*nova_ssh_key.*)', '') | search(":")
