---
- include: ceph.yml
  when:
    - enable_ceph | bool and nova_backend == "rbd"
    - inventory_hostname in groups['ceph-mon'] or
        inventory_hostname in groups['compute'] or
        inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['nova-conductor'] or
        inventory_hostname in groups['nova-consoleauth'] or
        inventory_hostname in groups['nova-novncproxy'] or
        inventory_hostname in groups['nova-scheduler']

- include: external-ceph.yml
  when:
    - enable_ceph | bool == False and nova_backend == "rbd"
    - inventory_hostname in groups['compute']

- include: register.yml
  when: inventory_hostname in groups['nova-api']

- include: config.yml
  when: inventory_hostname in groups['compute'] or
        inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['nova-conductor'] or
        inventory_hostname in groups['nova-consoleauth'] or
        inventory_hostname in groups['nova-novncproxy'] or
        inventory_hostname in groups['nova-scheduler']

- include: config-nova-fake.yml
  when:
    - enable_nova_fake | bool
    - inventory_hostname in groups['compute']

- include: bootstrap.yml
  when: inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['compute']

- include: start.yml
  when: inventory_hostname in groups['compute'] or
        inventory_hostname in groups['nova-api'] or
        inventory_hostname in groups['nova-conductor'] or
        inventory_hostname in groups['nova-consoleauth'] or
        inventory_hostname in groups['nova-novncproxy'] or
        inventory_hostname in groups['nova-scheduler']
