---
- name: Starting nova-libvirt container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_libvirt_image_full }}"
    name: "nova_libvirt"
    pid_mode: "host"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/nova-libvirt/:{{ container_config_directory }}/:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/run/:/run/"
      - "/sys/fs/cgroup:/sys/fs/cgroup"
      - "nova_compute:/var/lib/nova/"
      - "nova_libvirt:/var/lib/libvirt"
  when: inventory_hostname in groups['compute']

- name: Starting nova-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_api_image_full }}"
    name: "nova_api"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/nova-api/:{{ container_config_directory }}/:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/run/kolla/log:/dev/log"
  when: inventory_hostname in groups['nova-api']

- name: Starting nova-conductor container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    name: "nova_conductor"
    image: "{{ nova_conductor_image_full }}"
    volumes:
      - "{{ node_config_directory }}/nova-conductor/:{{ container_config_directory }}/:ro"
      - "/run/kolla/log:/dev/log"
  when: inventory_hostname in groups['nova-conductor']

- name: Starting nova-consoleauth container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_consoleauth_image_full }}"
    name: "nova_consoleauth"
    volumes:
      - "{{ node_config_directory }}/nova-consoleauth/:{{ container_config_directory }}/:ro"
      - "/run/kolla/log:/dev/log"
  when: inventory_hostname in groups['nova-consoleauth']

- name: Starting nova-novncproxy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_novncproxy_image_full }}"
    name: "nova_novncproxy"
    volumes:
      - "{{ node_config_directory }}/nova-novncproxy/:{{ container_config_directory }}/:ro"
      - "/run/kolla/log:/dev/log"
  when:
    - inventory_hostname in groups['nova-novncproxy']
    - nova_console == 'novnc'

- name: Starting nova-scheduler container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_scheduler_image_full }}"
    name: "nova_scheduler"
    volumes:
      - "{{ node_config_directory }}/nova-scheduler/:{{ container_config_directory }}/:ro"
      - "/run/kolla/log:/dev/log"
  when: inventory_hostname in groups['nova-scheduler']

- name: Starting nova-spicehtml5proxy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_spicehtml5proxy_image_full }}"
    name: "nova_spicehtml5proxy"
    volumes:
      - "{{ node_config_directory }}/nova-spicehtml5proxy/:{{ container_config_directory }}/:ro"
      - "/run/kolla/log:/dev/log"
  when:
    - inventory_hostname in groups['nova-spicehtml5proxy']
    - nova_console == 'spice'

- name: Starting nova-compute container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_compute_image_full }}"
    name: "nova_compute"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/nova-compute/:{{ container_config_directory }}/:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/run:/run"
      - "/run/kolla/log:/dev/log"
      - "nova_compute:/var/lib/nova/"
      - "nova_libvirt:/var/lib/libvirt"
  when:
    - inventory_hostname in groups['compute']
    - not enable_nova_fake | bool

- name: Starting nova-compute-ironic container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_compute_ironic_image_full }}"
    name: "nova_compute_ironic"
    volumes:
      - "{{ node_config_directory }}/nova-compute-ironic/:{{ container_config_directory }}/:ro"
      - "/run/kolla/log:/dev/log"
  when:
    - inventory_hostname in groups['nova-compute-ironic']
    - enable_ironic | bool

- name: Starting nova-compute-fake containers
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_compute_image_full }}"
    name: "nova_compute_fake_{{ item }}"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/nova-compute-fake-{{ item }}/:{{ container_config_directory }}/:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/run:/run"
      - "/run/kolla/log:/dev/log"
  with_sequence: start=1 end={{ num_nova_fake_per_node }}
  when:
    - inventory_hostname in groups['compute']
    - enable_nova_fake | bool
