---
- name: Starting nova-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_api_image_full }}"
    name: "nova_api"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/nova-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['nova-api']

- name: Starting nova-consoleauth container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_consoleauth_image_full }}"
    name: "nova_consoleauth"
    volumes:
      - "{{ node_config_directory }}/nova-consoleauth/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['nova-consoleauth']

- name: Starting nova-novncproxy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_novncproxy_image_full }}"
    name: "nova_novncproxy"
    volumes:
      - "{{ node_config_directory }}/nova-novncproxy/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when:
    - inventory_hostname in groups['nova-novncproxy']
    - nova_console == 'novnc'

- name: Starting nova-scheduler container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_scheduler_image_full }}"
    name: "nova_scheduler"
    volumes:
      - "{{ node_config_directory }}/nova-scheduler/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['nova-scheduler']

- name: Starting nova-spicehtml5proxy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ nova_spicehtml5proxy_image_full }}"
    name: "nova_spicehtml5proxy"
    volumes:
      - "{{ node_config_directory }}/nova-spicehtml5proxy/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when:
    - inventory_hostname in groups['nova-spicehtml5proxy']
    - nova_console == 'spice'
