---
- name: Starting heka container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      KOLLA_CONFIG_STRATEGY: "{{ config_strategy }}"
      SKIP_LOG_SETUP: "true"
    image: "{{ heka_image_full }}"
    name: "heka"
    volumes:
      - "{{ node_config_directory }}/heka/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
      - "heka:/var/cache/hekad"
      - "heka_socket:/var/lib/kolla/heka/"

- name: Starting kolla-toolbox container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    environment:
      ANSIBLE_NOCOLOR: "1"
      ANSIBLE_LIBRARY: "/usr/share/ansible"
    image: "{{ kolla_toolbox_image_full }}"
    name: "kolla_toolbox"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/kolla-toolbox/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/run/:/run/"
      - "kolla_logs:/var/log/kolla/"

- name: Initializing toolbox container using normal user
  command: docker exec -t kolla_toolbox /usr/bin/ansible --version
  changed_when: false

- name: Starting cron container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ cron_image_full }}"
    name: "cron"
    volumes:
      - "{{ node_config_directory }}/cron/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "heka_socket:/var/lib/kolla/heka/"
      - "kolla_logs:/var/log/kolla/"
