---
# Path to the kolla config file.
kolla_build_config_path: /etc/kolla/kolla-build.conf

# Dict of configuration to add to kolla-build.conf.
# Format:
# kolla_build_config:
#   "section":
#     "option name": "option value"
kolla_build_config: {}

# Dict mapping project names to sections in kolla-build.conf.
kolla_build_sources:
  openstack/requirements: openstack-base

  openstack/aodh: aodh-base
  openstack/barbican: barbican-base
  openstack/bifrost: bifrost-base
  openstack/blazar: blazar-base
  openstack/blazar-nova: nova-base-plugin-blazar
  openstack/ceilometer: ceilometer-base
  openstack/cinder: cinder-base
  openstack/cloudkitty: cloudkitty-base
  openstack/designate: designate-base
  openstack/glance: glance-base
  openstack/gnocchi: gnocchi-base
  openstack/heat: heat-base
  openstack/ironic: ironic-base
  openstack/keystone: keystone-base
  openstack/kuryr: kuryr-base
  openstack/kuryr-libnetwork: kuryr-libnetwork
  openstack/magnum: magnum-base
  openstack/manila: manila-base
  openstack/mistral: mistral-base
  openstack/monasca-agent: monasca-agent
  openstack/monasca-api: monasca-api
  openstack/monasca-notification: monasca-notification
  openstack/monasca-persister: monasca-persister
  openstack/monasca-statsd: monasca-statsd
  openstack/monasca-common: monasca-thresh-additions-monasca-common
  openstack/neutron: neutron-base
  openstack/networking-baremetal: neutron-base-plugin-networking-baremetal
  openstack/neutron-dynamic-routing:
    - neutron-bgp-dragent
    - neutron-server-plugin-neutron-dynamic-routing
  openstack/networking-infoblox: neutron-server-plugin-networking-infoblox
  openstack/networking-generic-switch: neutron-base-plugin-networking-generic-switch
  openstack/networking-sfc:
    - neutron-base-plugin-networking-sfc
    - tacker-base-plugin-networking-sfc
  openstack/neutron-vpnaas:
    - neutron-vpnaas-agent
    - neutron-base-plugin-vpnaas-agent
  openstack/nova: nova-base
  openstack/octavia: octavia-base
  openstack/skyline: skyline-base
  openstack/tacker:
    - tacker-base
    - mistral-base-plugin-tacker
  openstack/trove: trove-base
  openstack/venus: venus-base
  openstack/watcher: watcher-base
  openstack/zun: zun-base

  # Horizon and its plugins
  openstack/horizon: horizon
  openstack/blazar-dashboard: horizon-plugin-blazar-dashboard
  openstack/cloudkitty-dashboard: horizon-plugin-cloudkitty-dashboard
  openstack/designate-dashboard: horizon-plugin-designate-dashboard
  openstack/heat-dashboard: horizon-plugin-heat-dashboard
  openstack/ironic-ui: horizon-plugin-ironic-ui
  openstack/magnum-ui: horizon-plugin-magnum-ui
  openstack/manila-ui: horizon-plugin-manila-ui
  openstack/mistral-dashboard: horizon-plugin-mistral-dashboard
  openstack/monasca-ui: horizon-plugin-monasca-ui
  openstack/neutron-vpnaas-dashboard: horizon-plugin-neutron-vpnaas-dashboard
  openstack/octavia-dashboard: horizon-plugin-octavia-dashboard
  openstack/tacker-horizon: horizon-plugin-tacker-dashboard
  openstack/trove-dashboard: horizon-plugin-trove-dashboard
  openstack/venus-dashboard: horizon-plugin-venus-dashboard
  openstack/watcher-dashboard: horizon-plugin-watcher-dashboard
  openstack/zun-ui: horizon-plugin-zun-ui
