---
- name: Starting haproxy container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ haproxy_image_full }}"
    name: "haproxy"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/haproxy/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "haproxy_socket:/var/lib/kolla/haproxy/"
      - "heka_socket:/var/lib/kolla/heka/"

- name: Starting keepalived container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ keepalived_image_full }}"
    name: "keepalived"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/keepalived/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "haproxy_socket:/var/lib/kolla/haproxy/"
      - "heka_socket:/var/lib/kolla/heka/"

- name: Ensuring latest haproxy config is used
  command: docker exec haproxy /usr/local/bin/kolla_ensure_haproxy_latest_config
  register: status
  changed_when: status.stdout.find('changed') != -1

- name: Waiting for virtual IP to appear
  wait_for:
    host: "{{ kolla_internal_vip_address }}"
    port: "{{ database_port }}"
