---
- include: register.yml
  when: inventory_hostname in groups['ironic-api']

- include: config.yml
  when: inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-conductor'] or
        inventory_hostname in groups['ironic-inspector'] or
        inventory_hostname in groups['ironic-pxe']

- include: bootstrap.yml
  when: inventory_hostname in groups['ironic-api']

- include: start.yml
  when: inventory_hostname in groups['ironic-api'] or
        inventory_hostname in groups['ironic-conductor'] or
        inventory_hostname in groups['ironic-inspector'] or
        inventory_hostname in groups['ironic-pxe']
