desiredState:
  manifest:
    containers:
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: CEILOMETER_DB_PASSWORD
        value: ceilometerdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-ceilometer-api
      name: ceilometer-api
      ports:
      - containerPort: 8777
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: CEILOMETER_DB_PASSWORD
        value: ceilometerdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-ceilometer-notification
      name: ceilometer-notification
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: CEILOMETER_DB_PASSWORD
        value: ceilometerdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-ceilometer-central
      name: ceilometer-central
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: CEILOMETER_DB_PASSWORD
        value: ceilometerdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-ceilometer-collector
      name: ceilometer-collector
    - env:
      - name: DB_ROOT_PASSWORD
        value: password
      - name: CEILOMETER_DB_PASSWORD
        value: ceilometerdbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-ceilometer-alarm
      name: ceilometer-alarm
    id: ceilometer-1
    version: v1beta1
id: ceilometer
labels:
  name: ceilometer-controller
