apiVersion: v1beta1
kind: Pod
desiredState:
  manifest:
    containers:
    - env:
      - name: KEYSTONE_DB_PASSWORD
        value: password
      - name: DB_ROOT_PASSWORD
        value: password
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      image: kollaglue/fedora-rdo-keystone
      name: keystone
      ports:
      - containerPort: 5000
      - containerPort: 35357
    id: keystone-1
    version: v1beta1
id: keystone
labels:
  name: keystone
