desiredState:
  manifest:
    containers:
      - name: neutron-linux-bridge
        image: kollaglue/fedora-rdo-linux-bridge:l3_ovs_wip
        env:
          - name: CONFIG_NETWORK
            value: true
          - name: NEUTRON_KEYSTONE_PASSWORD
            value: password
      - name: neutron-l3-agent
        image: kollaglue/fedora-rdo-l3:l3_ovs_wip
        env:
          - name: NEUTRON_KEYSTONE_PASSWORD
            value: password
      - name: neutron-dhcp-agent
        image: kollaglue/fedora-rdo-dhcp:l3_ovs_wip
        env:
          - name: NEUTRON_KEYSTONE_PASSWORD
            value: password
      - name: neutron-metadata-agent
        image: kollaglue/fedora-rdo-metadata:l3_ovs_wip
        env:
          - name: NEUTRON_KEYSTONE_PASSWORD
            value: password
    id: neutron-network-1
    version: v1beta1
id: neutron-network
labels:
  name: neutron-network
