desiredState:
  manifest:
    volumes:
      - name: neutron-data
        source:
          emptyDir: {}
    containers:
      - name: neutron-server
        env:
          - name: DB_ROOT_PASSWORD
            value: password
          - name: NEUTRON_DB_PASSWORD
            value: password
          - name: NEUTRON_KEYSTONE_PASSWORD
            value: password
          - name: KEYSTONE_ADMIN_TOKEN
            value: ADMINTOKEN
          - name: NOVA_ADMIN_PASSWORD
            value: kolla
        image: kollaglue/fedora-rdo-neutron-server:l3_ovs_wip
        ports:
          - containerPort: 9696
        volumeMounts:
          - name: neutron-data
            mountPath: /var/lib/neutron
    id: neutron-server-1
    version: v1beta1
id: neutron-server
labels:
  name: neutron-server
