apiVersion: v1beta1
kind: Pod
desiredState:
  manifest:
    containers:
      - name: nova-compute
        env:
          - name: DB_ROOT_PASSWORD
            value: password
          - name: NOVA_DB_PASSWORD
            value: novadbpassword
          - name: KEYSTONE_ADMIN_TOKEN
            value: ADMINTOKEN
        image: kollaglue/fedora-rdo-nova-compute
        privileged: true
      - name: nova-network
        env:
          - name: DB_ROOT_PASSWORD
            value: password
          - name: NOVA_DB_PASSWORD
            value: novadbpassword
          - name: KEYSTONE_ADMIN_TOKEN
            value: ADMINTOKEN
          - name: CONFIG_NETWORK
            value: true
        image: kollaglue/fedora-rdo-nova-network
        privileged: true
      - name: ceilometer-compute
        env:
          - name: DB_ROOT_PASSWORD
            value: password
          - name: CEILOMETER_DB_PASSWORD
            value: ceilometerdbpassword
          - name: KEYSTONE_ADMIN_TOKEN
            value: ADMINTOKEN
        image: kollaglue/fedora-rdo-ceilometer-compute
    id: nova-1
    version: v1beta1
id: nova-compute
labels:
  name: nova-compute
