apiVersion: v1beta1
kind: Pod
desiredState:
  manifest:
    containers:
    - env:
      - name: NETWORK_MANAGER
        value: neutron
      - name: DB_ROOT_PASSWORD
        value: password
      - name: NOVA_DB_PASSWORD
        value: novadbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      - name: NEUTRON_SHARED_SECRET
        value: sharedsecret
      image: kollaglue/fedora-rdo-nova-conductor:l3_ovs_wip
      name: nova-conductor
    - env:
      - name: NETWORK_MANAGER
        value: neutron
      - name: DB_ROOT_PASSWORD
        value: password
      - name: NOVA_DB_PASSWORD
        value: novadbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      - name: NEUTRON_SHARED_SECRET
        value: sharedsecret
      image: kollaglue/fedora-rdo-nova-scheduler:l3_ovs_wip
      name: nova-scheduler
    - env:
      - name: NETWORK_MANAGER
        value: neutron
      - name: DB_ROOT_PASSWORD
        value: password
      - name: NOVA_DB_PASSWORD
        value: novadbpassword
      - name: KEYSTONE_ADMIN_TOKEN
        value: ADMINTOKEN
      - name: NEUTRON_SHARED_SECRET
        value: sharedsecret
      image: kollaglue/fedora-rdo-nova-api:l3_ovs_wip
      name: nova-api
      privileged: true
    id: nova-1
    version: v1beta1
id: nova-controller
labels:
  name: nova-controller
