---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "aodh-api"
    - "aodh-evaluator"
    - "aodh-listener"
    - "aodh-notifier"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "aodh-api"
    - "aodh-listener"
    - "aodh-evaluator"
    - "aodh-notifier"

- name: Copying over aodh.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/aodh.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/aodh.conf"
      - "{{ node_custom_config }}/aodh/{{ item }}.conf"
      - "{{ node_custom_config }}/aodh/{{ inventory_hostname }}/{{ item }}.conf"
    dest: "{{ node_config_directory }}/{{ item }}/aodh.conf"
  with_items:
    - "aodh-api"
    - "aodh-evaluator"
    - "aodh-listener"
    - "aodh-notifier"

- name: Copying over wsgi-aodh files for services
  template:
    src: "wsgi-aodh.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/wsgi-aodh.conf"
  with_items:
    - "aodh-api"
