---
- name: Starting cinder-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    name: "cinder_api"
    image: "{{ cinder_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/cinder-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['cinder-api']

- name: Starting cinder-scheduler container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    name: "cinder_scheduler"
    image: "{{ cinder_scheduler_image_full }}"
    volumes:
      - "{{ node_config_directory }}/cinder-scheduler/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['cinder-scheduler']

- name: Prepare volumes list for cinder-volume
  set_fact:
     cinder_volume_mounts:
      - "{{ node_config_directory }}/cinder-volume/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/run/:/run/"
      - "{% if enable_iscsid | bool %}cinder:/var/lib/cinder{% endif %}"
      - "{% if enable_iscsid | bool %}iscsi_info:/etc/iscsi{% endif %}"
      - "kolla_logs:/var/log/kolla/"

- name: Starting cinder-volume container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    name: "cinder_volume"
    image: "{{ cinder_volume_image_full }}"
    privileged: True
    ipc_mode: "host"
    volumes: '{{ cinder_volume_mounts | reject("equalto", "") | list}}'
  when: inventory_hostname in groups['cinder-volume']

- name: Prepare volumes list for cinder-backup
  set_fact:
     cinder_backup_mounts:
      - "{{ node_config_directory }}/cinder-backup/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/run/:/run/"
      - "{% if enable_cinder_backend_lvm | bool %}cinder:/var/lib/cinder{% endif %}"
      - "{% if enable_cinder_backend_lvm | bool %}iscsi_info:/etc/iscsi{% endif %}"
      - "kolla_logs:/var/log/kolla/"

- name: Starting cinder-backup container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    name: "cinder_backup"
    image: "{{ cinder_backup_image_full }}"
    privileged: True
    volumes: '{{ cinder_backup_mounts | reject("equalto", "") | list}}'
  when: inventory_hostname in groups['cinder-backup']
