---
- include: do_reconfigure.yml
  when: inventory_hostname in groups['swift-account-server'] or
        inventory_hostname in groups['swift-container-server'] or
        inventory_hostname in groups['swift-object-server'] or
        inventory_hostname in groups['swift-proxy-server']
