---
- name: Ensuring the containers up
  kolla_docker:
    name: "influxdb"
    action: "get_container_state"
  register: container_state
  failed_when: container_state.Running == false
  when: inventory_hostname in groups['influxdb']

- include: config.yml

- name: Check the configs
  command: docker exec influxdb /usr/local/bin/kolla_set_configs --check
  changed_when: false
  failed_when: false
  register: check_results
  when: inventory_hostname in groups['influxdb']

# NOTE(jeffrey4l): when config_strategy == 'COPY_ALWAYS'
# and container env['KOLLA_CONFIG_STRATEGY'] == 'COPY_ONCE',
# just remove the container and start again
- name: Containers config strategy
  kolla_docker:
    name: "influxdb"
    action: "get_container_env"
  register: container_envs
  when: inventory_hostname in groups['influxdb']

- name: Remove the containers
  kolla_docker:
    name: "influxdb"
    action: "remove_container"
  register: remove_containers
  when:
    - config_strategy == "COPY_ONCE"
    - inventory_hostname in groups['influxdb']

- include: start.yml
  when: remove_containers.changed

- name: Restart containers
  kolla_docker:
    name: "influxdb"
    action: "restart_container"
  when:
    - config_strategy == 'COPY_ALWAYS'
    - inventory_hostname in groups['influxdb']
