---
project_name: "magnum"

####################
# Database
####################
magnum_database_name: "magnum"
magnum_database_user: "magnum"
magnum_database_address: "{{ kolla_internal_fqdn }}:{{ database_port }}"


####################
# Docker
####################
magnum_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-magnum-api"
magnum_api_tag: "{{ openstack_release }}"
magnum_api_image_full: "{{ magnum_api_image }}:{{ magnum_api_tag }}"
magnum_conductor_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-magnum-conductor"
magnum_conductor_tag: "{{ openstack_release }}"
magnum_conductor_image_full: "{{ magnum_conductor_image }}:{{ magnum_conductor_tag }}"


####################
# OpenStack
####################
magnum_admin_endpoint: "{{ admin_protocol }}://{{ kolla_internal_fqdn }}:{{ magnum_api_port }}/v1"
magnum_internal_endpoint: "{{ internal_protocol }}://{{ kolla_internal_fqdn }}:{{ magnum_api_port }}/v1"
magnum_public_endpoint: "{{ public_protocol }}://{{ kolla_external_fqdn }}:{{ magnum_api_port }}/v1"

magnum_logging_debug: "{{ openstack_logging_debug }}"

magnum_keystone_user: "magnum"
magnum_trustee_domain_admin: "magnum_trustee_domain_admin"
magnum_trustee_domain: "magnum"

openstack_magnum_auth: "{'auth_url':'{{ openstack_auth.auth_url }}','username':'{{ openstack_auth.username }}','password':'{{ openstack_auth.password }}','project_name':'{{ openstack_auth.project_name }}'}"
