---
collections:
  - name: ansible.posix
    version: '<3'
  - name: community.general
    version: '<13'
  - name: community.mysql
    version: '<5'
  - name: community.rabbitmq
    version: '<2'
  - name: openstack.cloud
    version: '<3'
  - name: openvswitch.openvswitch
    version: '<3'
