---
- name: Starting heat-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ heat_api_image_full }}"
    name: "heat_api"
    volumes:
      - "{{ node_config_directory }}/heat-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['heat-api']

- name: Starting heat-api-cfn container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ heat_api_cfn_image_full }}"
    name: "heat_api_cfn"
    volumes:
      - "{{ node_config_directory }}/heat-api-cfn/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['heat-api-cfn']

- name: Starting heat-engine container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ heat_engine_image_full }}"
    name: "heat_engine"
    volumes:
      - "{{ node_config_directory }}/heat-engine/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['heat-engine']
