---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "bifrost"

- name: Generate bifrost configs
  merge_yaml:
    sources:
      - "{{ role_path }}/templates/{{ item }}.yml.j2"
      - "{{ node_custom_config }}/{{ item }}.yml"
      - "{{ node_custom_config }}/bifrost/{{ item }}.yml"
    dest: "{{ node_config_directory }}/bifrost/{{ item }}.yml"
  with_items:
    - "bifrost"
    - "dib"
    - "servers"

- name: template ssh keys
  template:
    src: "{{ item.src }}"
    dest: "{{ node_config_directory }}/bifrost/{{ item.dest }}"
  with_items:
    - { src: "id_rsa", dest: "id_rsa" }
    - { src: "id_rsa.pub", dest: "id_rsa.pub" }
    - { src: "ssh_config", dest: "ssh_config" }

