---
- include: register.yml
  when: inventory_hostname in groups['senlin-api']

- include: config.yml
  when: inventory_hostname in groups['senlin-api'] or
        inventory_hostname in groups['senlin-engine']

- include: bootstrap.yml
  when: inventory_hostname in groups['senlin-api']

- include: start.yml
  when: inventory_hostname in groups['senlin-api'] or
        inventory_hostname in groups['senlin-engine']
