---
- name: Starting sahara-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ sahara_api_image_full }}"
    name: "sahara_api"
    volumes:
      - "{{ node_config_directory }}/sahara-api/:{{ container_config_directory }}/:ro"
      - "sahara:/var/lib/sahara/"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['sahara-api']

- name: Starting sahara-engine container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ sahara_engine_image_full }}"
    name: "sahara_engine"
    volumes:
      - "{{ node_config_directory }}/sahara-engine/:{{ container_config_directory }}/:ro"
      - "sahara:/var/lib/sahara/"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['sahara-engine']
