---
- name: Ensuring config directories exist
  file:
    path: "{{ node_config_directory }}/{{ item }}"
    state: "directory"
    recurse: yes
  with_items:
    - "mistral-api"
    - "mistral-engine"
    - "mistral-executor"

- name: Copying over config.json files for services
  template:
    src: "{{ item }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item }}/config.json"
  with_items:
    - "mistral-api"
    - "mistral-engine"
    - "mistral-executor"

- name: Copying over mistral.conf
  merge_configs:
    vars:
      service_name: "{{ item }}"
    sources:
      - "{{ role_path }}/templates/mistral.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/database.conf"
      - "{{ node_custom_config }}/messaging.conf"
      - "{{ node_custom_config }}/mistral.conf"
      - "{{ node_custom_config }}/mistral/{{ item }}.conf"
      - "{{ node_custom_config }}/mistral/{{ inventory_hostname }}/mistral.conf"
    dest: "{{ node_config_directory }}/{{ item }}/mistral.conf"
  with_items:
    - "mistral-api"
    - "mistral-engine"
    - "mistral-executor"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/mistral/policy.json"
  register: mistral_policy

- name: Copying over existing policy.json
  template:
    src: "{{ node_custom_config }}/mistral/policy.json"
    dest: "{{ node_config_directory }}/mistral/policy.json"
  when:
    mistral_policy.stat.exists
