---
- name: Starting mistral-engine container
  kolla_docker:
    action: "start_container"
    name: "mistral_engine"
    common_options: "{{docker_common_options}}"
    image: "{{ mistral_engine_image_full }}"
    volumes:
      - "{{ node_config_directory }}/mistral-engine/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['mistral-engine']

- name: Starting mistral-executor container
  kolla_docker:
    action: "start_container"
    name: "mistral_executor"
    common_options: "{{docker_common_options}}"
    image: "{{ mistral_executor_image_full }}"
    volumes:
      - "{{ node_config_directory }}/mistral-executor/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['mistral-executor']

- name: Starting mistral-api container
  kolla_docker:
    action: "start_container"
    name: "mistral_api"
    common_options: "{{docker_common_options}}"
    image: "{{ mistral_api_image_full }}"
    volumes:
      - "{{ node_config_directory }}/mistral-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['mistral-api']
