---
- name: Starting designate-central container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ designate_central_image_full }}"
    name: "designate_central"
    volumes:
      - "{{ node_config_directory }}/designate-central/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['designate-central']

- name: Starting designate-api container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ designate_api_image_full }}"
    name: "designate_api"
    volumes:
      - "{{ node_config_directory }}/designate-api/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['designate-api']

- name: Starting designate-mdns container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ designate_mdns_image_full }}"
    name: "designate_mdns"
    volumes:
      - "{{ node_config_directory }}/designate-mdns/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['designate-mdns']

- name: Starting designate-pool-manager container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ designate_pool_manager_image_full }}"
    name: "designate_pool_manager"
    volumes:
      - "{{ node_config_directory }}/designate-pool-manager/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['designate-pool-manager']

- name: Starting designate-sink container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ designate_sink_image_full }}"
    name: "designate_sink"
    volumes:
      - "{{ node_config_directory }}/designate-sink/:{{ container_config_directory }}/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "kolla_logs:/var/log/kolla/"
  when: inventory_hostname in groups['designate-sink']
